YK integration
teknomavi/Kargo pull request #4
Opened 2020-06-19 12:30 UTC by selahaddinh

YK Yeni Kargo olusturma fonksiyonu eklendi

2020-06-22 14:17 UTC, selahaddinh commented
changed some test cases

2020-06-24 08:04 UTC, selahaddinh commented
getShipmentByReferenceNumber ve getShipmentByReferenceNumberList eklendi.

2020-06-30 10:09 UTC, GoktugOzturk requested changes
Değiştirilmesi gereken yerlere comment yazdım.

2020-06-30 10:09 UTC, GoktugOzturk commented on src/Company/Yurtici/Helper/YKSoapClient.php
> +    public function querryShipment($cargoKey)
method ismindeki `querry` kelimesinde typo var.

2020-06-30 10:09 UTC, GoktugOzturk commented on src/Company/Yurtici/Service.php
> +        if (property_exists($res->ShippingDeliveryVO->shippingDeliveryDetailVO->shippingDeliveryItemDetailVO, 'trackingUrl')) {
DRY

2020-06-30 10:09 UTC, GoktugOzturk commented on src/Company/Yurtici/Service.php
> +        if (property_exists($res->ShippingDeliveryVO->shippingDeliveryDetailVO, 'errCode')) {
DRY

2020-06-30 10:09 UTC, GoktugOzturk commented on src/Company/Yurtici/Service.php
> +            switch ($opCode) {
switch/case yerine $statusMapping array'ını ve mapStatus metodunu kullanabilirsin.

2020-06-30 10:09 UTC, GoktugOzturk commented on src/Company/Yurtici/Service.php
> +        array_push($this->packages, $package);
Shipment objesini addPackage fonksiyonu içinde oluşturup packages listesinde hazır objeyi tutuyoruz. Büyük listelerle sorgu yaptığımızda memory'de gereksiz obje tutmamak için böyle bir yol izliyoruz.

2020-07-01 13:19 UTC, GoktugOzturk requested changes

2020-07-01 13:19 UTC, GoktugOzturk commented on src/Company/Yurtici/Service.php
> +    public function mapStatus(string $originalStatus): string
mapStatus fonksiyonu Abstract class'dan geliyor. Tekrar yazmana gerek yok.

2020-07-01 13:19 UTC, GoktugOzturk commented on src/Company/Yurtici/Service.php
> +        if (property_exists($res->ShippingDeliveryVO->shippingDeliveryDetailVO->shippingDeliveryItemDetailVO, 'trackingUrl')) {
Bu kısım isErrorMessage fonksiyonu içinde olmamalı. Ayrı bir fonksiyon yapıp onu kullanırsan daha iyi olur.

2020-07-01 13:19 UTC, GoktugOzturk commented on src/Company/Yurtici/Service.php
> +            return [$packageInfo, true];
response içinde @packageInfo'yu dönmene gerek yok sanırım. Gönderdiğin parametre önceki objeye link olduğu için bu fonksiyonda çağırdığın o objeye ait metodlar aynı datayı değiştirecektir ve önceki metodda kullanabilirsin.

2020-07-01 13:19 UTC, GoktugOzturk commented on src/Company/Yurtici/Service.php
> +        $this->statusMapping = array(
statusMapping'i class variable olarak tanımlayabilirsin. Constructor'da doldurmana gerek yok. Örnek: https://github.com/teknomavi/Kargo/blob/master/src/Company/Ups/Service.php

2020-07-02 19:57 UTC, GoktugOzturk approved these changes

2020-07-02 19:58 UTC, merged